apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service-deployment
  labels:
    app: match-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      containers:
      - name: match-service
        imagePullPolicy: IfNotPresent
        image: segment17hub/matchservice:0.1.1
        ports:
        - containerPort: 50053
        env:
          - name: MATCH_MYSQL_SERVICE_ADDR
            value: "match-mysql-service"
          - name: AUTH_SERVICE_ADDR
            value: "auth-service:50051"
          - name: BOXER_SERVICE_ADDR
            value: "boxer-service:50052"
          - name: MATCH_SERVICE_ADDR
            value: "match-service:50053"
---
apiVersion: v1
kind: Service
metadata:
  name: match-service
  labels:
    app: match-service
spec:
  type: ClusterIP
  selector:
    app: match-service
  ports:
    - name: grpc
      port: 50053
      targetPort: 50053
---
# MYSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-mysql-deployment
spec:
  selector:
    matchLabels:
      app: matchmysql
  template:
    metadata:
      labels:
        app: matchmysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
          - name: match-mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: match-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: match-mysql-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: match-mysql-service
spec:
  selector:
    app: matchmysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: match-mysql-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# MYSQL
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: match-service
spec:
  grpc: True
  prefix: /ubc_package.MatchService/
  rewrite: /ubc_package.MatchService/
  service: match-service:50053
---
